In [96]:
import pandas as pd

In [97]:
df = pd.read_csv("../data/raw/cars_details_merged.csv")

C:\Users\hp\AppData\Local\Temp\ipykernel_5028\2058076775.py:1: DtypeWarning: Columns (0: priceSaving, 1: brandingIcon) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/cars_details_merged.csv")

In [98]:
df.head()

,position,loc,myear,bt,tt,ft,km,ip,pi,images,...,owner_type,price_segment_new,template_name_new,page_template,template_Type_new,experiment,Fuel Suppy System,Compression Ratio,Alloy Wheel Size,Ground Clearance Unladen
0,1,Gomti Nagar,2016,Hatchback,Manual,CNG,"69,162",0,https://images10.gaadi.com/usedcar_image/origi...,[{'img': 'https://images10.gaadi.com/usedcar_i...,...,first,2lakh-5lakh,used cardetail v2/corporate/13,Used Car > Detail Page,used,control,NaN,NaN,NaN,NaN
1,2,Borivali West,2015,Hatchback,Manual,CNG,"45,864",0,https://images10.gaadi.com/usedcar_image/origi...,[{'img': 'https://images10.gaadi.com/usedcar_i...,...,first,2lakh-5lakh,used cardetail v2/corporate/13,Used Car > Detail Page,used,control,Intelligent-Gas Port Injection,11.0:1,NaN,NaN
2,3,JASOLA,2015,Sedan,Manual,CNG,"81,506",0,https://images10.gaadi.com/usedcar_image/origi...,[{'img': 'https://images10.gaadi.com/usedcar_i...,...,second,2lakh-5lakh,used cardetail v2/corporate/13,Used Car > Detail Page,used,control,NaN,NaN,NaN,NaN
3,4,jasola,2013,Hatchback,Manual,CNG,"1,15,893",0,NaN,[{'img': ''}],...,second,2lakh-5lakh,used cardetail v2/corporate/13,Used Car > Detail Page,used,control,MPFI,NaN,13,NaN
4,5,mumbai g.p.o.,2022,MUV,Manual,CNG,"18,900",0,https://images10.gaadi.com/usedcar_image/origi...,[{'img': 'https://images10.gaadi.com/usedcar_i...,...,first,10+lakh,used cardetail v2,Used Car > Detail Page,used,control,NaN,12.0+-.03,NaN,NaN

In [99]:
df.shape

(37814, 140)

In [100]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37814 entries, 0 to 37813
Columns: 140 entries, position to Ground Clearance Unladen
dtypes: bool(3), float64(10), int64(28), str(99)
memory usage: 39.6 MB

In [101]:
df.columns

Index(['position', 'loc', 'myear', 'bt', 'tt', 'ft', 'km', 'ip', 'pi',
       'images',
       ...
       'owner_type', 'price_segment_new', 'template_name_new', 'page_template',
       'template_Type_new', 'experiment', 'Fuel Suppy System',
       'Compression Ratio', 'Alloy Wheel Size', 'Ground Clearance Unladen'],
      dtype='str', length=140)

In [102]:
df.isnull().sum()

position                        0
loc                          5851
myear                           0
bt                             19
tt                              0
                            ...
experiment                      0
Fuel Suppy System            5502
Compression Ratio           27642
Alloy Wheel Size            13146
Ground Clearance Unladen    35662
Length: 140, dtype: int64

In [103]:
df.head().T

,0,1,2,3,4
position,1,2,3,4,5
loc,Gomti Nagar,Borivali West,JASOLA,jasola,mumbai g.p.o.
myear,2016,2015,2015,2013,2022
bt,Hatchback,Hatchback,Sedan,Hatchback,MUV
tt,Manual,Manual,Manual,Manual,Manual
...,...,...,...,...,...
experiment,control,control,control,control,control
Fuel Suppy System,NaN,Intelligent-Gas Port Injection,NaN,MPFI,NaN
Compression Ratio,NaN,11.0:1,NaN,NaN,12.0+-.03
Alloy Wheel Size,NaN,NaN,NaN,13,NaN
Ground Clearance Unladen,NaN,NaN,NaN,NaN,NaN

In [104]:
df[['price', 'pu']].head()

          price         pu
0   ₹ 3.70 Lakh   3,70,000
1   ₹ 3.65 Lakh   3,65,000
2   ₹ 4.21 Lakh   4,21,000
3   ₹ 2.40 Lakh   2,40,000
4  ₹ 11.75 Lakh  11,75,000

In [105]:
df[['price', 'pu']].dtypes

price    str
pu       str
dtype: object

In [106]:
df['pu'].head()

0     3,70,000
1     3,65,000
2     4,21,000
3     2,40,000
4    11,75,000
Name: pu, dtype: str

In [107]:
df['pu'] = df['pu'].str.replace(',', '')

In [108]:
df['pu'].head()

0     370000
1     365000
2     421000
3     240000
4    1175000
Name: pu, dtype: str

In [109]:
df['pu'] = df['pu'].astype(int)

In [110]:
df["pu"].dtype

dtype('int64')

In [111]:
df.columns.tolist()

['position',
 'loc',
 'myear',
 'bt',
 'tt',
 'ft',
 'km',
 'ip',
 'pi',
 'images',
 'imgCount',
 'threesixty',
 'dvn',
 'oem',
 'model',
 'modelId',
 'vid',
 'centralVariantId',
 'variantName',
 'city_x',
 'vlink',
 'price',
 'pu',
 'discountValue',
 'msp',
 'priceSaving',
 'pageNo',
 'utype',
 'views',
 'usedCarId',
 'usedCarSkuId',
 'ucid',
 'sid',
 'tmGaadiStore',
 'emiwidget',
 'transmissionType',
 'dynx_itemid_x',
 'dynx_itemid2_x',
 'dynx_totalvalue_x',
 'leadForm',
 'leadFormCta',
 'offers',
 'compare',
 'brandingIcon',
 'pageType',
 'carType',
 'corporateId',
 'top_features',
 'comfort_features',
 'interior_features',
 'exterior_features',
 'safety_features',
 'Color',
 'Engine Type',
 'Displacement',
 'Max Power',
 'Max Torque',
 'No of Cylinder',
 'Values per Cylinder',
 'Value Configuration',
 'BoreX Stroke',
 'Turbo Charger',
 'Super Charger',
 'Length',
 'Width',
 'Height',
 'Wheel Base',
 'Front Tread',
 'Rear Tread',
 'Kerb Weight',
 'Gross Weight',
 'Gear Box',
 'Drive Type',
 'Seating Capacity',
 'Steering Type',
 'Turning Radius',
 'Front Brake Type',
 'Rear Brake Type',
 'Top Speed',
 'Acceleration',
 'Tyre Type',
 'No Door Numbers',
 'Cargo Volumn',
 'model_type_new',
 'originalLocation',
 'page_title',
 'compare_car_details',
 'seller_type_new',
 'seating_capacity_new',
 'transmission_type',
 'model_year_new',
 'car_type_new',
 'model_name',
 'model_id_new',
 'oem_name',
 'price_range_segment',
 'dealer_id_new',
 'state',
 'city_id_new',
 'fuel_type',
 'max_engine_capacity_new',
 'transmission_type_new',
 'km_driven',
 'model_new',
 'vehicle_type_new',
 'brand_name',
 'engine_cc',
 'fuel_type_new',
 'car_segment',
 'used_carid',
 'city_name_new',
 'page_type',
 'city_y',
 'engine_capacity_new',
 'body_type_new',
 'owner_type_new',
 'mileage_new',
 'dealer_id',
 'model_year',
 'variant_name',
 'price_segment',
 'dynx_event',
 'dynx_pagetype',
 'dynx_itemid_y',
 'dynx_itemid2_y',
 'dynx_totalvalue_y',
 'brand_new',
 'variant_new',
 'exterior_color',
 'min_engine_capacity_new',
 'owner_type',
 'price_segment_new',
 'template_name_new',
 'page_template',
 'template_Type_new',
 'experiment',
 'Fuel Suppy System',
 'Compression Ratio',
 'Alloy Wheel Size',
 'Ground Clearance Unladen']

In [112]:
columns_to_drop = [
    'ip',
    'pi',
    'images',
    'imgCount',
    'threesixty',
    'vlink',
    'brandingIcon',
    'pageType',
    'pageNo',
    'views',
    'leadForm',
    'leadFormCta',
    'offers',
    'compare',
    'emiwidget'
]

df.drop(columns=columns_to_drop, inplace=True)

In [113]:
df[['ft', 'fuel_type', 'fuel_type_new']].head(10)

    ft fuel_type fuel_type_new
0  CNG       cng           cng
1  CNG       cng           cng
2  CNG       cng           cng
3  CNG       cng           cng
4  CNG       cng           cng
5  CNG       cng           cng
6  CNG       cng           cng
7  CNG       cng           cng
8  CNG       cng           cng
9  CNG       cng           cng

In [114]:
(df['ft'].str.lower() == df['fuel_type']).all()

np.False_

In [115]:
df[df['ft'].str.lower() != df['fuel_type']][['ft', 'fuel_type']].head(20)

           ft fuel_type
2802   Diesel    petrol
9778   Diesel    petrol
36271  Petrol    diesel

In [116]:
df.loc[[2802, 9778, 36271], [
    'oem',
    'model',
    'variantName',
    'ft',
    'fuel_type',
    'fuel_type_new',
    'dvn'
]]

,oem,model,variantName,ft,fuel_type,fuel_type_new,dvn
2802,Toyota,Toyota Fortuner,4x2 AT,Diesel,petrol,petrol,Toyota Fortuner 4x2 AT
9778,Kia,Kia Seltos,HTX Plus D,Diesel,petrol,petrol,Kia Seltos HTX Plus D
36271,Tata,Tata Tiago,1.2 Revotron XE,Petrol,diesel,diesel,Tata Tiago 1.2 Revotron XE

In [117]:
df[['tt', 'transmissionType', 'transmission_type', 'transmission_type_new']].sample(10, random_state=42)

              tt transmissionType transmission_type transmission_type_new
3288      Manual           Manual            manual                manual
36027     Manual           Manual            manual                manual
36286     Manual           Manual            manual                manual
21250     Manual           Manual            manual                manual
1453      Manual           Manual            manual                manual
2189      Manual           Manual            manual                manual
29472     Manual           Manual            manual                manual
24393  Automatic        Automatic         automatic             automatic
4751      Manual           Manual            manual                manual
28075     Manual           Manual            manual                manual

In [118]:

df[['myear', 'model_year', 'model_year_new']].sample(10, random_state=42)

       myear  model_year  model_year_new
3288    2016        2016            2016
36027   2014        2014            2014
36286   2020        2020            2020
21250   2018        2018            2018
1453    2017        2017            2017
2189    2011        2011            2011
29472   2016        2016            2016
24393   2019        2019            2019
4751    2018        2018            2018
28075   2013        2013            2013

In [119]:

df[['km', 'km_driven']].sample(10, random_state=42)

             km  km_driven
3288   1,50,000     150000
36027    53,755      53755
36286    53,838      53838
21250    28,112      28112
1453     63,125      63125
2189   1,20,000     120000
29472    27,227      27227
24393    20,388      20388
4751     75,000      75000
28075    49,000      49000

In [120]:

df[['oem', 'oem_name', 'brand_name']].sample(10, random_state=42)

            oem  oem_name brand_name
3288     Toyota    toyota     toyota
36027  Mahindra  mahindra   mahindra
36286      Tata      tata       tata
21250   Hyundai   hyundai    hyundai
1453     Maruti    maruti     maruti
2189     Toyota    toyota     toyota
29472     Honda     honda      honda
24393    Maruti    maruti     maruti
4751       Ford      ford       ford
28075   Hyundai   hyundai    hyundai

In [121]:
duplicate_columns = [
    'price',
    'fuel_type',
    'fuel_type_new',
    'oem_name',
    'brand_name',
    'model_year',
    'model_year_new',
    'km'
]

df.drop(columns=duplicate_columns, inplace=True)

In [122]:
df.shape

(37814, 117)

In [123]:
df.rename(columns={
    'pu': 'price',
    'oem': 'brand',
    'myear': 'model_year',
    'bt': 'body_type',
    'tt': 'transmission',
    'ft': 'fuel_type',
    'dvn': 'full_vehicle_name',
    'vid': 'vehicle_name'
}, inplace=True)

In [124]:
df.columns.tolist()

['position',
 'loc',
 'model_year',
 'body_type',
 'transmission',
 'fuel_type',
 'full_vehicle_name',
 'brand',
 'model',
 'modelId',
 'vehicle_name',
 'centralVariantId',
 'variantName',
 'city_x',
 'price',
 'discountValue',
 'msp',
 'priceSaving',
 'utype',
 'usedCarId',
 'usedCarSkuId',
 'ucid',
 'sid',
 'tmGaadiStore',
 'transmissionType',
 'dynx_itemid_x',
 'dynx_itemid2_x',
 'dynx_totalvalue_x',
 'carType',
 'corporateId',
 'top_features',
 'comfort_features',
 'interior_features',
 'exterior_features',
 'safety_features',
 'Color',
 'Engine Type',
 'Displacement',
 'Max Power',
 'Max Torque',
 'No of Cylinder',
 'Values per Cylinder',
 'Value Configuration',
 'BoreX Stroke',
 'Turbo Charger',
 'Super Charger',
 'Length',
 'Width',
 'Height',
 'Wheel Base',
 'Front Tread',
 'Rear Tread',
 'Kerb Weight',
 'Gross Weight',
 'Gear Box',
 'Drive Type',
 'Seating Capacity',
 'Steering Type',
 'Turning Radius',
 'Front Brake Type',
 'Rear Brake Type',
 'Top Speed',
 'Acceleration',
 'Tyre Type',
 'No Door Numbers',
 'Cargo Volumn',
 'model_type_new',
 'originalLocation',
 'page_title',
 'compare_car_details',
 'seller_type_new',
 'seating_capacity_new',
 'transmission_type',
 'car_type_new',
 'model_name',
 'model_id_new',
 'price_range_segment',
 'dealer_id_new',
 'state',
 'city_id_new',
 'max_engine_capacity_new',
 'transmission_type_new',
 'km_driven',
 'model_new',
 'vehicle_type_new',
 'engine_cc',
 'car_segment',
 'used_carid',
 'city_name_new',
 'page_type',
 'city_y',
 'engine_capacity_new',
 'body_type_new',
 'owner_type_new',
 'mileage_new',
 'dealer_id',
 'variant_name',
 'price_segment',
 'dynx_event',
 'dynx_pagetype',
 'dynx_itemid_y',
 'dynx_itemid2_y',
 'dynx_totalvalue_y',
 'brand_new',
 'variant_new',
 'exterior_color',
 'min_engine_capacity_new',
 'owner_type',
 'price_segment_new',
 'template_name_new',
 'page_template',
 'template_Type_new',
 'experiment',
 'Fuel Suppy System',
 'Compression Ratio',
 'Alloy Wheel Size',
 'Ground Clearance Unladen']

In [125]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage.sort_values(ascending=False)

originalLocation            100.000000
compare_car_details         100.000000
priceSaving                  99.994711
Ground Clearance Unladen     94.308986
Compression Ratio            73.099910
                               ...
variant_new                   0.000000
experiment                    0.000000
template_Type_new             0.000000
page_template                 0.000000
template_name_new             0.000000
Length: 117, dtype: float64

In [126]:
metadata_columns = [
    "usedCarId",
    "usedCarSkuId",
    "ucid",
    "sid",
    "corporateId",
    "dynx_itemid_x",
    "dynx_itemid2_x",
    "dynx_totalvalue_x",
    "dynx_itemid_y",
    "dynx_itemid2_y",
    "dynx_totalvalue_y",
    "dynx_event",
    "dynx_pagetype",
    "dealer_id",
    "dealer_id_new",
    "modelId",
    "model_id_new",
    "city_id_new",
    "page_type",
    "experiment",
    "template_name_new",
    "page_template",
    "template_Type_new"
]

df = df.drop(columns=metadata_columns)
df.shape

(37814, 94)

In [127]:
high_missing = missing_percentage[missing_percentage > 40]



len(high_missing)

9

In [128]:
high_missing

priceSaving                  99.994711
BoreX Stroke                 66.581160
Front Tread                  41.981806
Rear Tread                   41.984450
Gross Weight                 55.244089
originalLocation            100.000000
compare_car_details         100.000000
Compression Ratio            73.099910
Ground Clearance Unladen     94.308986
dtype: float64

In [129]:
columns_to_drop = [
    "priceSaving",
    "originalLocation",
    "compare_car_details",
    "Ground Clearance Unladen",
    "Compression Ratio",
    "BoreX Stroke",
    "Gross Weight",
    "Front Tread",
    "Rear Tread"
]

df = df.drop(columns=columns_to_drop)

df.shape

(37814, 85)

In [130]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage[
    (missing_percentage > 0) &
    (missing_percentage <= 40)
].sort_values(ascending=False)

Top Speed                  39.763051
Acceleration               36.991590
Alloy Wheel Size           34.764902
Kerb Weight                34.746390
Value Configuration        20.709261
Cargo Volumn               17.802930
loc                        15.473105
Turning Radius             15.465172
Fuel Suppy System          14.550167
Super Charger              14.142910
Drive Type                 11.889776
Turbo Charger               5.754482
mileage_new                 2.382715
Engine Type                 2.295446
Steering Type               2.136775
Wheel Base                  1.467710
Gear Box                    1.076321
Width                       0.981118
Height                      0.959962
Length                      0.957317
Front Brake Type            0.864759
Rear Brake Type             0.862115
Tyre Type                   0.679642
Max Power                   0.610885
Max Torque                  0.610885
Values per Cylinder         0.602951
engine_capacity_new         0.425768
engine_cc                   0.425768
Color                       0.423124
No of Cylinder              0.378167
exterior_color              0.325276
min_engine_capacity_new     0.140160
Displacement                0.140160
max_engine_capacity_new     0.140160
No Door Numbers             0.116359
seating_capacity_new        0.076691
body_type                   0.050246
car_segment                 0.050246
Seating Capacity            0.047601
dtype: float64

In [131]:
df["loc"].value_counts().head(20)

loc
Pune City           2110
Gurgaon             1716
Bangalore City      1588
New Delhi G.P.O.    1417
pune city           1373
gurgaon             1044
new delhi g.p.o.     932
bangalore city       909
Mahadevapura         826
Noida                772
Ghaziabad            755
Surat                669
Dehradun             651
Lucknow G.P.O.       548
Thathawade           518
Goregaon East        461
Ahmedabad            438
Jaipur               427
Vadodara             383
Hyderabad            378
Name: count, dtype: int64

In [132]:
df[["loc", "city_x"]].sample(10, random_state=42)

                    loc     city_x
3288                NaN     Nagpur
36027  new delhi g.p.o.  New Delhi
36286         SECTOR 39      Noida
21250          Dehradun   Dehradun
1453     kandivali west     Mumbai
2189                NaN      Harur
29472         Pune City       Pune
24393    Bangalore City  Bangalore
4751                NaN     Guntur
28075     borivali west     Mumbai

In [133]:
columns_to_drop = [
    "Top Speed",
    "Acceleration",
    "Alloy Wheel Size",
    "Kerb Weight",
    "Value Configuration",
    "Cargo Volumn",
    "Turning Radius",
    "loc"
]

df = df.drop(columns=columns_to_drop)
df.shape

(37814, 77)

In [134]:
df.dtypes.value_counts()

str        60
int64       8
float64     8
bool        1
Name: count, dtype: int64

In [135]:
categorical_cols = df.select_dtypes(include="object").columns

numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns

boolean_cols = df.select_dtypes(include="bool").columns

len(categorical_cols), len(numerical_cols), len(boolean_cols)

C:\Users\hp\AppData\Local\Temp\ipykernel_5028\4111603932.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

(60, 16, 1)

In [136]:
missing_counts = df.isnull().sum()

missing_counts = missing_counts[missing_counts > 0].sort_values(ascending=False)

missing_counts

Fuel Suppy System          5502
Super Charger              5348
Drive Type                 4496
Turbo Charger              2176
mileage_new                 901
Engine Type                 868
Steering Type               808
Wheel Base                  555
Gear Box                    407
Width                       371
Height                      363
Length                      362
Front Brake Type            327
Rear Brake Type             326
Tyre Type                   257
Max Torque                  231
Max Power                   231
Values per Cylinder         228
engine_cc                   161
engine_capacity_new         161
Color                       160
No of Cylinder              143
exterior_color              123
min_engine_capacity_new      53
Displacement                 53
max_engine_capacity_new      53
No Door Numbers              44
seating_capacity_new         29
body_type                    19
car_segment                  19
Seating Capacity             18
dtype: int64

In [137]:
mode_columns = [
    "Fuel Suppy System",
    "Super Charger",
    "Drive Type",
    "Turbo Charger",
    "Engine Type",
    "Steering Type",
    "Gear Box",
    "Front Brake Type",
    "Rear Brake Type",
    "Tyre Type",
    "Color",
    "exterior_color",
    "body_type",
    "car_segment",
    "mileage_new"
]

for column in mode_columns:
    df[column] = df[column].fillna(df[column].mode()[0])

In [138]:
df[mode_columns].isnull().sum()

Fuel Suppy System    0
Super Charger        0
Drive Type           0
Turbo Charger        0
Engine Type          0
Steering Type        0
Gear Box             0
Front Brake Type     0
Rear Brake Type      0
Tyre Type            0
Color                0
exterior_color       0
body_type            0
car_segment          0
mileage_new          0
dtype: int64

In [139]:
columns_to_drop = [
    "mileage_new",
    "min_engine_capacity_new",
    "max_engine_capacity_new"
]

df = df.drop(columns=columns_to_drop)
df.shape

(37814, 74)

In [140]:
missing_counts = df.isnull().sum()
missing_counts = missing_counts[missing_counts > 0].sort_values(ascending=False)

missing_counts

Wheel Base              555
Width                   371
Height                  363
Length                  362
Max Torque              231
Max Power               231
Values per Cylinder     228
engine_capacity_new     161
engine_cc               161
No of Cylinder          143
Displacement             53
No Door Numbers          44
seating_capacity_new     29
Seating Capacity         18
dtype: int64

In [141]:
df[["Seating Capacity", "seating_capacity_new"]].sample(10, random_state=42)

       Seating Capacity  seating_capacity_new
3288                7.0                   7.0
36027               7.0                   7.0
36286               5.0                   5.0
21250               5.0                   5.0
1453                7.0                   7.0
2189                7.0                   7.0
29472               5.0                   5.0
24393               5.0                   5.0
4751                5.0                   5.0
28075               5.0                   5.0

In [142]:
df[["engine_cc", "engine_capacity_new"]].sample(10, random_state=42)

           engine_cc engine_capacity_new
3288   2000cc-3000cc       2000cc-3000cc
36027  2000cc-3000cc       2000cc-3000cc
36286  1000cc-2000cc       1000cc-2000cc
21250  1000cc-2000cc       1000cc-2000cc
1453   1000cc-2000cc       1000cc-2000cc
2189   2000cc-3000cc       2000cc-3000cc
29472  1000cc-2000cc       1000cc-2000cc
24393   500cc-1000cc        500cc-1000cc
4751   1000cc-2000cc       1000cc-2000cc
28075  1000cc-2000cc       1000cc-2000cc

In [143]:
df = df.drop(
    columns=[
        "seating_capacity_new",
        "engine_capacity_new"
    ]
)

missing_counts = df.isnull().sum()
missing_counts = missing_counts[missing_counts > 0].sort_values(ascending=False)

missing_counts

Wheel Base             555
Width                  371
Height                 363
Length                 362
Max Torque             231
Max Power              231
Values per Cylinder    228
engine_cc              161
No of Cylinder         143
Displacement            53
No Door Numbers         44
Seating Capacity        18
dtype: int64

In [144]:
df[["Displacement", "Max Power", "Max Torque"]].sample(10, random_state=42)

       Displacement           Max Power                Max Torque
3288         2494.0    100.6bhp@3600rpm        200Nm@1200-3600rpm
36027        2179.0      140bhp@3750rpm        330Nm@1600-2800rpm
36286        1199.0    84.88bhp@6000rpm             113nm@3300rpm
21250        1591.0    121.3bhp@6400rpm             151Nm@4850rpm
1453         1248.0     88.5bhp@4000rpm             200Nm@1750rpm
2189         2494.0  102@3,600 (PS@rpm)  20.4@1400-3400 (kgm@rpm)
29472        1199.0     88.7bhp@6000rpm             110Nm@4800rpm
24393         998.0    67.05bhp@6000rpm              90Nm@3500rpm
4751         1498.0    98.63bhp@3750rpm        215Nm@1750-3000rpm
28075        1197.0       82bhp@6000rpm             114Nm@4000rpm

In [145]:
df["Max Power"] = (
    df["Max Power"]
    .str.extract(r"(\d+\.?\d*)")
    .astype(float)
)

df["Max Torque"] = (
    df["Max Torque"]
    .str.extract(r"(\d+\.?\d*)")
    .astype(float)
)

df[["Max Power", "Max Torque"]].head()

   Max Power  Max Torque
0      58.16        77.0
1      58.20        78.0
2      86.70       109.0
3      58.20        77.0
4      86.63       121.5

In [148]:
measurement_cols = [
    "Wheel Base",
    "Width",
    "Height",
    "Length"
]

for col in measurement_cols:
    df[col] = (
        df[col]
        .str.extract(r"(\d+\.?\d*)")
        .astype(float)
    )

In [149]:
median_columns = [
    "Wheel Base",
    "Width",
    "Height",
    "Length",
    "Max Torque",
    "Max Power",
    "Values per Cylinder",
    "Displacement",
    "No of Cylinder",
    "No Door Numbers",
    "Seating Capacity"
]

for column in median_columns:
    df[column]= df[column].fillna(df[column].median())

df["engine_cc"] = df["engine_cc"].fillna(
    df["engine_cc"].mode()[0]
)

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [150]:
df.dtypes.value_counts()

str        52
float64    11
int64       8
bool        1
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [151]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37814 entries, 0 to 37813
Data columns (total 72 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   position               37814 non-null  int64
 1   model_year             37814 non-null  int64
 2   body_type              37814 non-null  str
 3   transmission           37814 non-null  str
 4   fuel_type              37814 non-null  str
 5   full_vehicle_name      37814 non-null  str
 6   brand                  37814 non-null  str
 7   model                  37814 non-null  str
 8   vehicle_name           37814 non-null  str
 9   centralVariantId       37814 non-null  int64
 10  variantName            37814 non-null  str
 11  city_x                 37814 non-null  str
 12  price                  37814 non-null  int64
 13  discountValue          37814 non-null  int64
 14  msp                    37814 non-null  int64
 15  utype                  37814 non-null  str
 16  tmGaadiStore           37814 non-null  bool
 17  transmissionType       37814 non-null  str
 18  carType                37814 non-null  str
 19  top_features           37814 non-null  str
 20  comfort_features       37814 non-null  str
 21  interior_features      37814 non-null  str
 22  exterior_features      37814 non-null  str
 23  safety_features        37814 non-null  str
 24  Color                  37814 non-null  str
 25  Engine Type            37814 non-null  str
 26  Displacement           37814 non-null  float64
 27  Max Power              37814 non-null  float64
 28  Max Torque             37814 non-null  float64
 29  No of Cylinder         37814 non-null  float64
 30  Values per Cylinder    37814 non-null  float64
 31  Turbo Charger          37814 non-null  str
 32  Super Charger          37814 non-null  str
 33  Length                 37814 non-null  float64
 34  Width                  37814 non-null  float64
 35  Height                 37814 non-null  float64
 36  Wheel Base             37814 non-null  float64
 37  Gear Box               37814 non-null  str
 38  Drive Type             37814 non-null  str
 39  Seating Capacity       37814 non-null  float64
 40  Steering Type          37814 non-null  str
 41  Front Brake Type       37814 non-null  str
 42  Rear Brake Type        37814 non-null  str
 43  Tyre Type              37814 non-null  str
 44  No Door Numbers        37814 non-null  float64
 45  model_type_new         37814 non-null  str
 46  page_title             37814 non-null  str
 47  seller_type_new        37814 non-null  str
 48  transmission_type      37814 non-null  str
 49  car_type_new           37814 non-null  str
 50  model_name             37814 non-null  str
 51  price_range_segment    37814 non-null  str
 52  state                  37814 non-null  str
 53  transmission_type_new  37814 non-null  str
 54  km_driven              37814 non-null  int64
 55  model_new              37814 non-null  str
 56  vehicle_type_new       37814 non-null  str
 57  engine_cc              37814 non-null  str
 58  car_segment            37814 non-null  str
 59  used_carid             37814 non-null  int64
 60  city_name_new          37814 non-null  str
 61  city_y                 37814 non-null  str
 62  body_type_new          37814 non-null  str
 63  owner_type_new         37814 non-null  str
 64  variant_name           37814 non-null  str
 65  price_segment          37814 non-null  str
 66  brand_new              37814 non-null  str
 67  variant_new            37814 non-null  str
 68  exterior_color         37814 non-null  str
 69  owner_type             37814 non-null  str
 70  price_segment_new      37814 non-null  str
 71  Fuel Suppy System      37814 non-null  str
dtypes: bool(1), float64(11), int64(8), str(52)
memory usage: 20.5 MB

In [152]:
df[["Max Power", "Max Torque"]].dtypes

Max Power     float64
Max Torque    float64
dtype: object

In [154]:
df.shape

(37814, 72)

In [155]:
df.isnull().sum().sum()

np.int64(0)

In [156]:
df.dtypes.value_counts()

str        52
float64    11
int64       8
bool        1
Name: count, dtype: int64

In [157]:
df.duplicated().sum()

np.int64(0)

In [158]:
df[
    [
        "Wheel Base",
        "Width",
        "Height",
        "Length",
        "Max Power",
        "Max Torque"
    ]
].head()

   Wheel Base   Width  Height  Length  Max Power  Max Torque
0      2400.0  1495.0  1700.0  3599.0      58.16        77.0
1      2425.0  1600.0  1560.0  3600.0      58.20        78.0
2      2405.0  1680.0  1505.0  3990.0      86.70       109.0
3      2400.0  1475.0  1700.0  3595.0      58.20        77.0
4      2740.0  1735.0  1690.0  4395.0      86.63       121.5

In [159]:
df.describe()

,position,model_year,centralVariantId,price,discountValue,msp,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Length,Width,Height,Wheel Base,Seating Capacity,No Door Numbers,km_driven,used_carid
count,37814.000000,37814.000000,37814.000000,3.781400e+04,37814.000000,3.781400e+04,37814.000000,37814.000000,37814.000000,37814.000000,37814.000000,37814.000000,37814.000000,37814.000000,37814.000000,37814.000000,37814.000000,3.781400e+04,3.781400e+04
mean,12.786349,2015.569472,4244.333131,7.999749e+05,73.279764,5.426562e+01,1438.371344,102.667119,178.566183,3.820093,3.894589,4073.184693,1709.863014,1562.441556,2502.459803,5.236605,4.664489,6.240934e+04,3.350110e+06
std,4.538626,3.779047,2456.207209,3.043006e+06,2805.746196,7.477465e+03,470.283655,42.667429,106.058787,0.540510,0.477119,555.300301,207.480116,188.305063,361.003264,0.722088,0.496367,5.847148e+04,4.822178e+04
min,1.000000,1983.000000,3.000000,1.196300e+04,0.000000,0.000000e+00,0.000000,10.800000,4.800000,1.000000,1.000000,3.000000,1.000000,1.000000,2.000000,0.000000,2.000000,1.010000e+02,2.123741e+06
25%,9.000000,2013.000000,1689.000000,3.200000e+05,0.000000,0.000000e+00,1197.000000,75.000000,110.000000,4.000000,4.000000,3780.000000,1677.000000,1495.000000,2425.000000,5.000000,4.000000,3.173950e+04,3.323254e+06
50%,13.000000,2016.000000,4191.000000,5.250000e+05,0.000000,0.000000e+00,1248.000000,88.500000,145.000000,4.000000,4.000000,3995.000000,1710.000000,1530.000000,2520.000000,5.000000,5.000000,5.672600e+04,3.366214e+06
75%,17.000000,2018.000000,6373.000000,8.552040e+05,0.000000,0.000000e+00,1582.000000,118.350000,220.000000,4.000000,4.000000,4430.000000,1790.000000,1640.000000,2636.000000,5.000000,5.000000,8.330775e+04,3.384768e+06
max,20.000000,2023.000000,9670.000000,5.500006e+08,200000.000000,1.093000e+06,6749.000000,769.310000,900.000000,16.000000,48.000000,5982.000000,2236.000000,2075.000000,3772.000000,14.000000,6.000000,6.300000e+06,3.399050e+06

In [160]:
df["fuel_type"].value_counts()

fuel_type
Petrol      21773
Diesel      14630
CNG          1076
LPG           205
Electric      130
Name: count, dtype: int64

In [161]:
df.nlargest(10, "price")[
    [
        "brand",
        "model",
        "variantName",
        "model_year",
        "price"
    ]
]

,brand,model,variantName,model_year,price
5091,Ford,Ford Ecosport,1.5 TDCi Titanium BSIV,2016,550000555
13638,Rolls-Royce,Rolls-Royce Phantom,Extended Wheelbase,2021,95519530
2766,Ferrari,Ferrari SF90 Stradale,Coupe V8,2022,44425000
2764,Ferrari,Ferrari 488 GTB,Spider,2020,32570569
13634,Lamborghini,Lamborghini Huracan EVO,Spyder RWD,2021,29999999
7533,Mercedes-Benz,Mercedes-Benz Maybach S-Class,S580,2022,28300000
2760,Lamborghini,Lamborghini Huracan,LP 610 4 BSIV,2015,22500000
2768,Lamborghini,Lamborghini Huracan,LP 610 4 BSIV,2015,22500000
2774,Aston Martin,Aston Martin Vantage,V8 4.7L,2019,21100000
7348,Mercedes-Benz,Mercedes-Benz S-Class,S400d 4Matic,2021,19768726

In [162]:
df.nsmallest(10, "price")[
    [
        "brand",
        "model",
        "variantName",
        "model_year",
        "price"
    ]
]

           brand               model  variantName  model_year  price
1754        Tata  Tata Indigo Marina      LX BSII        2005  11963
16227     Maruti          Maruti 800     AC BSIII        2002  25000
2425      Maruti         Maruti Omni    5 Str STD        1990  40000
18229     Maruti          Maruti Zen         D PS        2001  40000
18242     Maruti          Maruti Zen       2 Door        1998  40000
19336     Maruti         Maruti Alto           LX        2005  40000
21784     Maruti          Maruti Zen  LX - BS III        2000  40000
18012     Maruti          Maruti 800          Std        2005  41000
8364   Chevrolet     Chevrolet Spark       1.0 LS        2009  44444
8988   Chevrolet     Chevrolet Spark       1.0 LS        2007  45000

In [163]:
df.loc[5091]

position                                                6
model_year                                           2016
body_type                                             SUV
transmission                                       Manual
fuel_type                                          Diesel
                                     ...
variant_new          ford ecosport 1.5 tdci titanium bsiv
exterior_color                                      White
owner_type                                          first
price_segment_new                                 10+lakh
Fuel Suppy System                        Direct Injection
Name: 5091, Length: 72, dtype: object

In [164]:
df = df.drop(index=5091)

In [165]:
df["price"].describe()

count    3.781300e+04
mean     7.854508e+05
std      1.132718e+06
min      1.196300e+04
25%      3.200000e+05
50%      5.250000e+05
75%      8.550000e+05
max      9.551953e+07
Name: price, dtype: float64

In [166]:
df.shape

(37813, 72)

In [167]:
df.to_csv("../data/processed/cleaned_used_cars.csv", index=False)