In [34]:
import pandas as pd

In [35]:
df = pd.read_csv("../data/raw/cars_details_merged.csv")

C:\Users\hp\AppData\Local\Temp\ipykernel_38264\2058076775.py:1: DtypeWarning: Columns (0: priceSaving, 1: brandingIcon) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/cars_details_merged.csv")

In [36]:
df.head()

,position,loc,myear,bt,tt,ft,km,ip,pi,images,...,owner_type,price_segment_new,template_name_new,page_template,template_Type_new,experiment,Fuel Suppy System,Compression Ratio,Alloy Wheel Size,Ground Clearance Unladen
0,1,Gomti Nagar,2016,Hatchback,Manual,CNG,"69,162",0,https://images10.gaadi.com/usedcar_image/origi...,[{'img': 'https://images10.gaadi.com/usedcar_i...,...,first,2lakh-5lakh,used cardetail v2/corporate/13,Used Car > Detail Page,used,control,NaN,NaN,NaN,NaN
1,2,Borivali West,2015,Hatchback,Manual,CNG,"45,864",0,https://images10.gaadi.com/usedcar_image/origi...,[{'img': 'https://images10.gaadi.com/usedcar_i...,...,first,2lakh-5lakh,used cardetail v2/corporate/13,Used Car > Detail Page,used,control,Intelligent-Gas Port Injection,11.0:1,NaN,NaN
2,3,JASOLA,2015,Sedan,Manual,CNG,"81,506",0,https://images10.gaadi.com/usedcar_image/origi...,[{'img': 'https://images10.gaadi.com/usedcar_i...,...,second,2lakh-5lakh,used cardetail v2/corporate/13,Used Car > Detail Page,used,control,NaN,NaN,NaN,NaN
3,4,jasola,2013,Hatchback,Manual,CNG,"1,15,893",0,NaN,[{'img': ''}],...,second,2lakh-5lakh,used cardetail v2/corporate/13,Used Car > Detail Page,used,control,MPFI,NaN,13,NaN
4,5,mumbai g.p.o.,2022,MUV,Manual,CNG,"18,900",0,https://images10.gaadi.com/usedcar_image/origi...,[{'img': 'https://images10.gaadi.com/usedcar_i...,...,first,10+lakh,used cardetail v2,Used Car > Detail Page,used,control,NaN,12.0+-.03,NaN,NaN

In [37]:
df.shape

(37814, 140)

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37814 entries, 0 to 37813
Columns: 140 entries, position to Ground Clearance Unladen
dtypes: bool(3), float64(10), int64(28), str(99)
memory usage: 39.6 MB

In [39]:
df.columns

Index(['position', 'loc', 'myear', 'bt', 'tt', 'ft', 'km', 'ip', 'pi',
       'images',
       ...
       'owner_type', 'price_segment_new', 'template_name_new', 'page_template',
       'template_Type_new', 'experiment', 'Fuel Suppy System',
       'Compression Ratio', 'Alloy Wheel Size', 'Ground Clearance Unladen'],
      dtype='str', length=140)

In [40]:
df.isnull().sum()

position                        0
loc                          5851
myear                           0
bt                             19
tt                              0
                            ...
experiment                      0
Fuel Suppy System            5502
Compression Ratio           27642
Alloy Wheel Size            13146
Ground Clearance Unladen    35662
Length: 140, dtype: int64

In [41]:
df.head().T

,0,1,2,3,4
position,1,2,3,4,5
loc,Gomti Nagar,Borivali West,JASOLA,jasola,mumbai g.p.o.
myear,2016,2015,2015,2013,2022
bt,Hatchback,Hatchback,Sedan,Hatchback,MUV
tt,Manual,Manual,Manual,Manual,Manual
...,...,...,...,...,...
experiment,control,control,control,control,control
Fuel Suppy System,NaN,Intelligent-Gas Port Injection,NaN,MPFI,NaN
Compression Ratio,NaN,11.0:1,NaN,NaN,12.0+-.03
Alloy Wheel Size,NaN,NaN,NaN,13,NaN
Ground Clearance Unladen,NaN,NaN,NaN,NaN,NaN

In [42]:
df[['price', 'pu']].head()

          price         pu
0   ₹ 3.70 Lakh   3,70,000
1   ₹ 3.65 Lakh   3,65,000
2   ₹ 4.21 Lakh   4,21,000
3   ₹ 2.40 Lakh   2,40,000
4  ₹ 11.75 Lakh  11,75,000

In [43]:
df[['price', 'pu']].dtypes

price    str
pu       str
dtype: object

In [44]:
df['pu'].head()

0     3,70,000
1     3,65,000
2     4,21,000
3     2,40,000
4    11,75,000
Name: pu, dtype: str

In [45]:
df['pu'] = df['pu'].str.replace(',', '')

In [46]:
df['pu'].head()

0     370000
1     365000
2     421000
3     240000
4    1175000
Name: pu, dtype: str

In [47]:
df['pu'] = df['pu'].astype(int)

In [48]:
df["pu"].dtype

dtype('int64')

In [49]:
df.columns.tolist()

['position',
 'loc',
 'myear',
 'bt',
 'tt',
 'ft',
 'km',
 'ip',
 'pi',
 'images',
 'imgCount',
 'threesixty',
 'dvn',
 'oem',
 'model',
 'modelId',
 'vid',
 'centralVariantId',
 'variantName',
 'city_x',
 'vlink',
 'price',
 'pu',
 'discountValue',
 'msp',
 'priceSaving',
 'pageNo',
 'utype',
 'views',
 'usedCarId',
 'usedCarSkuId',
 'ucid',
 'sid',
 'tmGaadiStore',
 'emiwidget',
 'transmissionType',
 'dynx_itemid_x',
 'dynx_itemid2_x',
 'dynx_totalvalue_x',
 'leadForm',
 'leadFormCta',
 'offers',
 'compare',
 'brandingIcon',
 'pageType',
 'carType',
 'corporateId',
 'top_features',
 'comfort_features',
 'interior_features',
 'exterior_features',
 'safety_features',
 'Color',
 'Engine Type',
 'Displacement',
 'Max Power',
 'Max Torque',
 'No of Cylinder',
 'Values per Cylinder',
 'Value Configuration',
 'BoreX Stroke',
 'Turbo Charger',
 'Super Charger',
 'Length',
 'Width',
 'Height',
 'Wheel Base',
 'Front Tread',
 'Rear Tread',
 'Kerb Weight',
 'Gross Weight',
 'Gear Box',
 'Drive Type',
 'Seating Capacity',
 'Steering Type',
 'Turning Radius',
 'Front Brake Type',
 'Rear Brake Type',
 'Top Speed',
 'Acceleration',
 'Tyre Type',
 'No Door Numbers',
 'Cargo Volumn',
 'model_type_new',
 'originalLocation',
 'page_title',
 'compare_car_details',
 'seller_type_new',
 'seating_capacity_new',
 'transmission_type',
 'model_year_new',
 'car_type_new',
 'model_name',
 'model_id_new',
 'oem_name',
 'price_range_segment',
 'dealer_id_new',
 'state',
 'city_id_new',
 'fuel_type',
 'max_engine_capacity_new',
 'transmission_type_new',
 'km_driven',
 'model_new',
 'vehicle_type_new',
 'brand_name',
 'engine_cc',
 'fuel_type_new',
 'car_segment',
 'used_carid',
 'city_name_new',
 'page_type',
 'city_y',
 'engine_capacity_new',
 'body_type_new',
 'owner_type_new',
 'mileage_new',
 'dealer_id',
 'model_year',
 'variant_name',
 'price_segment',
 'dynx_event',
 'dynx_pagetype',
 'dynx_itemid_y',
 'dynx_itemid2_y',
 'dynx_totalvalue_y',
 'brand_new',
 'variant_new',
 'exterior_color',
 'min_engine_capacity_new',
 'owner_type',
 'price_segment_new',
 'template_name_new',
 'page_template',
 'template_Type_new',
 'experiment',
 'Fuel Suppy System',
 'Compression Ratio',
 'Alloy Wheel Size',
 'Ground Clearance Unladen']

In [50]:
columns_to_drop = [
    'ip',
    'pi',
    'images',
    'imgCount',
    'threesixty',
    'vlink',
    'brandingIcon',
    'pageType',
    'pageNo',
    'views',
    'leadForm',
    'leadFormCta',
    'offers',
    'compare',
    'emiwidget'
]

df.drop(columns=columns_to_drop, inplace=True)

In [51]:
df[['ft', 'fuel_type', 'fuel_type_new']].head(10)

    ft fuel_type fuel_type_new
0  CNG       cng           cng
1  CNG       cng           cng
2  CNG       cng           cng
3  CNG       cng           cng
4  CNG       cng           cng
5  CNG       cng           cng
6  CNG       cng           cng
7  CNG       cng           cng
8  CNG       cng           cng
9  CNG       cng           cng

In [52]:
(df['ft'].str.lower() == df['fuel_type']).all()

np.False_

In [53]:
df[df['ft'].str.lower() != df['fuel_type']][['ft', 'fuel_type']].head(20)

           ft fuel_type
2802   Diesel    petrol
9778   Diesel    petrol
36271  Petrol    diesel

In [54]:
df.loc[[2802, 9778, 36271], [
    'oem',
    'model',
    'variantName',
    'ft',
    'fuel_type',
    'fuel_type_new',
    'dvn'
]]

,oem,model,variantName,ft,fuel_type,fuel_type_new,dvn
2802,Toyota,Toyota Fortuner,4x2 AT,Diesel,petrol,petrol,Toyota Fortuner 4x2 AT
9778,Kia,Kia Seltos,HTX Plus D,Diesel,petrol,petrol,Kia Seltos HTX Plus D
36271,Tata,Tata Tiago,1.2 Revotron XE,Petrol,diesel,diesel,Tata Tiago 1.2 Revotron XE

In [ ]:
df[['tt', 'transmissionType', 'transmission_type', 'transmission_type_new']].sample(10, random_state=42)

            oem  oem_name brand_name
3288     Toyota    toyota     toyota
36027  Mahindra  mahindra   mahindra
36286      Tata      tata       tata
21250   Hyundai   hyundai    hyundai
1453     Maruti    maruti     maruti
2189     Toyota    toyota     toyota
29472     Honda     honda      honda
24393    Maruti    maruti     maruti
4751       Ford      ford       ford
28075   Hyundai   hyundai    hyundai

In [57]:

df[['myear', 'model_year', 'model_year_new']].sample(10, random_state=42)

       myear  model_year  model_year_new
3288    2016        2016            2016
36027   2014        2014            2014
36286   2020        2020            2020
21250   2018        2018            2018
1453    2017        2017            2017
2189    2011        2011            2011
29472   2016        2016            2016
24393   2019        2019            2019
4751    2018        2018            2018
28075   2013        2013            2013

In [58]:

df[['km', 'km_driven']].sample(10, random_state=42)

             km  km_driven
3288   1,50,000     150000
36027    53,755      53755
36286    53,838      53838
21250    28,112      28112
1453     63,125      63125
2189   1,20,000     120000
29472    27,227      27227
24393    20,388      20388
4751     75,000      75000
28075    49,000      49000

In [59]:

df[['oem', 'oem_name', 'brand_name']].sample(10, random_state=42)

            oem  oem_name brand_name
3288     Toyota    toyota     toyota
36027  Mahindra  mahindra   mahindra
36286      Tata      tata       tata
21250   Hyundai   hyundai    hyundai
1453     Maruti    maruti     maruti
2189     Toyota    toyota     toyota
29472     Honda     honda      honda
24393    Maruti    maruti     maruti
4751       Ford      ford       ford
28075   Hyundai   hyundai    hyundai

In [60]:
duplicate_columns = [
    'price',
    'fuel_type',
    'fuel_type_new',
    'oem_name',
    'brand_name',
    'model_year',
    'model_year_new',
    'km'
]

df.drop(columns=duplicate_columns, inplace=True)

In [61]:
df.shape

(37814, 117)

In [62]:
df.rename(columns={
    'pu': 'price',
    'oem': 'brand',
    'myear': 'model_year',
    'bt': 'body_type',
    'tt': 'transmission',
    'ft': 'fuel_type',
    'dvn': 'full_vehicle_name',
    'vid': 'vehicle_name'
}, inplace=True)